package com.example.foodsearchspringserver.controller;

import com.example.foodsearchspringserver.payload.FromToKeyword;
import com.example.foodsearchspringserver.model.Keywords;
import com.example.foodsearchspringserver.service.KeywordService;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.util.MultiValueMap;
import org.springframework.web.bind.annotation.*;

import java.util.Map;
import java.util.logging.Logger;

//@RestController for raw json, @Controller for form payload
@Controller
@RequestMapping(path="/")
@CrossOrigin(origins = "http://localhost:4200")

public class KeywordController {

    @Autowired// This means to get the bean called KeywordRepository
    // Which is auto-generated by Spring, we will use it to handle the payload
    private KeywordService keywordService;

    @PostMapping(path="/post", consumes = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody Iterable<Keywords> addNewKeywordThenReturnAll(@RequestBody Keywords keywords) {
        return keywordService.postKeywords(keywords);
    }

    @GetMapping(path="/get")
    public @ResponseBody Iterable<Keywords> getAllUsers() {
        return keywordService.getKeywords();
    }

    @DeleteMapping(path="/delete", consumes = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody Iterable<Keywords> deleteUser(@RequestBody Keywords keywords) { //keywords is just a word/deceiving
        return keywordService.deleteKeywords(keywords);
    }

    @PutMapping(path="/put", consumes = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody Iterable<Keywords> changeUser(@RequestBody Map<String, String> fromToKeywords) {
        return keywordService.putKeywordsChangeUser(fromToKeywords);
    }
}
