package com.example.foodsearchspringserver.service;

import com.example.foodsearchspringserver.model.Keywords;
import com.example.foodsearchspringserver.repository.KeywordRepository;
import javassist.compiler.ast.Keyword;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.Map;

@Service
public class KeywordService {
    @Autowired// This means to get the bean called KeywordRepository
    // Which is auto-generated by Spring, we will use it to handle the payload
    private KeywordRepository keywordRepository;

    public Iterable<Keywords> postKeywords(Keywords keyword) {
        Keywords k = new Keywords();
        k.setKeyword(keyword.getKeyword());
        keywordRepository.save(k);
        return keywordRepository.findAll();
    }

    public Iterable<Keywords> getKeywords() {
        return keywordRepository.findAll();
    }

    public Iterable<Keywords> deleteKeywords(Keywords keyword) {
        // Returns JSON of keywords:
        keywordRepository.deleteKeyword(keyword.getKeyword());
        return keywordRepository.findAll();
    }

    public Iterable<Keywords> putKeywordsChangeUser(Map<String, String> fromToKeywords) {
        keywordRepository.changeKeyword(fromToKeywords.get("ChangeFromKeyword"), fromToKeywords.get("ChangeToKeyword"));
        return keywordRepository.findAll();
    }
}
